// tslint:disable:object-literal-key-quotes
export let conf = {
  patient: {
    conditions: {
      acme: {
        interactions: {
          priDiag: {
            name: "Primary Tumor Diagnosis",
            defaultFilter: '@INTERACTION.INTERACTION_TYPE = "ACME_M03"',
            attributes: {
              icd_10: {
                name: "ICD-10-CM Code",
                type: "text",
                expression: "SUBSTR(@CODE.VALUE,0,3)",
                defaultFilter: '@CODE.ATTRIBUTE = "ICD_10"',
                referenceExpression: "@REF.CODE",
                referenceFilter:
                  '@REF.CATALOG = "ICDO3.1-TOPO-DIMDI" AND LENGTH(@REF.CODE)=3',
                order: 1,
                useRefValue: true,
                useRefText: true,
              },
              icd_9: {
                name: "ICD-9-CM Code",
                type: "text",
                expression: "SUBSTR(@CODE.VALUE,0,3)",
                defaultFilter: '@CODE.ATTRIBUTE = "ICD_9"',
                order: 2,
              },
              age: {
                name: "Age at Diagnosis",
                type: "num",
                defaultFilter: '@PATIENT.DOB <= @INTERACTION."END"',
                expression:
                  'FLOOR(DAYS_BETWEEN(@PATIENT.DOB,@INTERACTION."END") / 365)',
                order: 3,
              },
              nsclc: {
                name: "Lung Cancer Subtype",
                type: "text",
                defaultFilter: '@CODE.ATTRIBUTE = "LC_TYPE"',
                expression: "@CODE.VALUE",
                order: 4,
              },
              freetextDiag: {
                name: "Diagnosis Free Text",
                type: "freetext",
                defaultFilter: '@TEXT.ATTRIBUTE = "INTERACTIONS_FREETEXT"',
                expression: "@TEXT.VALUE",
                fuzziness: 0.8,
                order: 5,
              },
              histology: {
                name: "Histology",
                type: "text",
                defaultFilter: '@CODE.ATTRIBUTE = "Histology"',
                expression: "@CODE.VALUE",
                order: 6,
              },
              tcgaCode: {
                name: "Cancer Abbreviation",
                type: "text",
                expression: "@CODE.VALUE",
                defaultFilter: '@CODE.ATTRIBUTE = "TCGA_CODE"',
                order: 7,
              },
              tcgaCancer: {
                name: "Cancer Type",
                type: "text",
                expression: "@CODE.VALUE",
                defaultFilter: '@CODE.ATTRIBUTE = "TCGA_CANCER"',
                order: 8,
              },
              calYear: {
                name: "Start Year",
                type: "num",
                expression: 'YEAR(@INTERACTION."START")',
                isDefault: true,
              },
              calMonth: {
                name: "Start Month",
                type: "num",
                expression: 'MONTH(@INTERACTION."START")',
                referenceFilter: '@REF.Catalog="HPH.MRI-MONTHS-CAT"',
                referenceExpression: "@REF.CODE",
                isDefault: true,
              },
              start: {
                name: "Start Date",
                type: "time",
                expression: '@INTERACTION."START"',
                isDefault: true,
              },
              end: {
                name: "End Date",
                type: "time",
                expression: '@INTERACTION."END"',
                isDefault: true,
              },
            },
          },
          biobank: {
            name: "Biobank",
            defaultFilter: '@INTERACTION.INTERACTION_TYPE = "BIOBANK"',
            attributes: {
              status: {
                name: "Sample Status",
                type: "text",
                defaultFilter: '@CODE.ATTRIBUTE = "BIOBANK_STATUS"',
                expression: "@CODE.VALUE",
              },
              tType: {
                name: "Tissue / Liquid Type",
                type: "text",
                defaultFilter: '@CODE.ATTRIBUTE = "BIOBANK_TYPE"',
                expression: "@CODE.VALUE",
              },
              calYear: {
                name: "Start Year",
                type: "num",
                expression: 'YEAR(@INTERACTION."START")',
                isDefault: true,
              },
              calMonth: {
                name: "Start Month",
                type: "num",
                expression: 'MONTH(@INTERACTION."START")',
                referenceFilter: '@REF.Catalog="HPH.MRI-MONTHS-CAT"',
                referenceExpression: "@REF.CODE",
                isDefault: true,
              },
              start: {
                name: "Start Date",
                type: "time",
                expression: '@INTERACTION."START"',
                isDefault: true,
              },
              end: {
                name: "End Date",
                type: "time",
                expression: '@INTERACTION."END"',
                isDefault: true,
              },
            },
          },
          chemo: {
            name: "Chemotherapy",
            defaultFilter: '@INTERACTION.INTERACTION_TYPE = "ACME_M07_CHEMO"',
            attributes: {
              interactionCount: {
                name: "Interaction Count",
                type: "num",
                measureExpression:
                  "COUNT(DISTINCT(@INTERACTION.INTERACTION_ID))",
                defaultFilter: "",
              },
              chemo_ops: {
                name: "OPS Code",
                type: "text",
                defaultFilter: '@CODE.ATTRIBUTE = "CHEMO_OPS"',
                expression: "@CODE.VALUE",
              },
              chemo_prot: {
                name: "Protocol",
                type: "text",
                defaultFilter: '@CODE.ATTRIBUTE = "CHEMO_PROT"',
                expression: "@CODE.VALUE",
              },
              interactionsPerPatient: {
                name: "Interactions per Patient",
                type: "num",
                measureExpression:
                  "COUNT(DISTINCT(@INTERACTION.INTERACTION_ID)) / COUNT(DISTINCT(@PATIENT.PATIENT_ID))",
                defaultFilter: "",
              },
              calYear: {
                name: "Start Year",
                type: "num",
                expression: 'YEAR(@INTERACTION."START")',
                isDefault: true,
              },
              calMonth: {
                name: "Start Month",
                type: "num",
                expression: 'MONTH(@INTERACTION."START")',
                referenceFilter: '@REF.Catalog="HPH.MRI-MONTHS-CAT"',
                referenceExpression: "@REF.CODE",
                isDefault: true,
              },
              start: {
                name: "Start Date",
                type: "time",
                expression: '@INTERACTION."START"',
                isDefault: true,
              },
              end: {
                name: "End Date",
                type: "time",
                expression: '@INTERACTION."END"',
                isDefault: true,
              },
            },
          },
          radio: {
            name: "Radiotherapy",
            defaultFilter: '@INTERACTION.INTERACTION_TYPE = "ACME_M07_RADIO"',
            attributes: {
              radio_dosage: {
                name: "Radio Dosage (Gy)",
                type: "num",
                defaultFilter:
                  '@MEASURE.ATTRIBUTE = "DOSAGE" AND @MEASURE.UNIT = "Gy"',
                expression: "@MEASURE.VALUE",
              },
              radio_ops: {
                name: "OPS Code",
                type: "text",
                defaultFilter: '@CODE.ATTRIBUTE = "RADIO_OPS"',
                expression: "@CODE.VALUE",
              },
              calYear: {
                name: "Start Year",
                type: "num",
                expression: 'YEAR(@INTERACTION."START")',
                isDefault: true,
              },
              calMonth: {
                name: "Start Month",
                type: "num",
                expression: 'MONTH(@INTERACTION."START")',
                referenceFilter: '@REF.Catalog="HPH.MRI-MONTHS-CAT"',
                referenceExpression: "@REF.CODE",
                isDefault: true,
              },
              start: {
                name: "Start Date",
                type: "time",
                expression: '@INTERACTION."START"',
                isDefault: true,
              },
              end: {
                name: "End Date",
                type: "time",
                expression: '@INTERACTION."END"',
                isDefault: true,
              },
            },
          },
          surgery: {
            name: "Surgery",
            defaultFilter: '@INTERACTION.INTERACTION_TYPE = "ACME_M07_SURGERY"',
            attributes: {
              exist: {
                name: "Exist",
                type: "text",
                expression:
                  'CASE WHEN @INTERACTION.INTERACTION_ID IS NULL THEN NULL ELSE "YES" END',
                defaultFilter: "",
              },
              surgery_ops: {
                name: "OPS Code",
                type: "text",
                defaultFilter: '@CODE.ATTRIBUTE = "SURGERY_OPS"',
                expression: "@CODE.VALUE",
              },
              calYear: {
                name: "Start Year",
                type: "num",
                expression: 'YEAR(@INTERACTION."START")',
                isDefault: true,
              },
              calMonth: {
                name: "Start Month",
                type: "num",
                expression: 'MONTH(@INTERACTION."START")',
                referenceFilter: '@REF.Catalog="HPH.MRI-MONTHS-CAT"',
                referenceExpression: "@REF.CODE",
                isDefault: true,
              },
              start: {
                name: "Start Date",
                type: "time",
                expression: '@INTERACTION."START"',
                isDefault: true,
              },
              end: {
                name: "End Date",
                type: "time",
                expression: '@INTERACTION."END"',
                isDefault: true,
              },
            },
          },
          tnm: {
            name: "TNM Classification",
            defaultFilter: '@INTERACTION.INTERACTION_TYPE = "ACME_M03TS"',
            attributes: {
              tnmM: {
                name: "M-Component",
                type: "text",
                defaultFilter: '@CODE.ATTRIBUTE = "TNM_M"',
                expression: '"M" || @CODE.VALUE',
              },
              tnmN: {
                name: "N-Component",
                type: "text",
                defaultFilter: '@CODE.ATTRIBUTE = "TNM_N"',
                expression: '"N" || @CODE.VALUE',
              },
              tnmT: {
                name: "T-Component",
                type: "text",
                defaultFilter: '@CODE.ATTRIBUTE = "TNM_T"',
                expression: '"T" || @CODE.VALUE',
              },
              calYear: {
                name: "Start Year",
                type: "num",
                expression: 'YEAR(@INTERACTION."START")',
                isDefault: true,
              },
              calMonth: {
                name: "Start Month",
                type: "num",
                expression: 'MONTH(@INTERACTION."START")',
                referenceFilter: '@REF.Catalog="HPH.MRI-MONTHS-CAT"',
                referenceExpression: "@REF.CODE",
                isDefault: true,
              },
              start: {
                name: "Start Date",
                type: "time",
                expression: '@INTERACTION."START"',
                isDefault: true,
              },
              end: {
                name: "End Date",
                type: "time",
                expression: '@INTERACTION."END"',
                isDefault: true,
              },
            },
          },
        },
        name: "Tumor Case",
      },
    },
    interactions: {
      vStatus: {
        name: "Vital Status",
        defaultFilter: '@INTERACTION.INTERACTION_TYPE = "ACME_M16"',
        attributes: {
          age: {
            name: "Age at Last Contact",
            type: "num",
            defaultFilter: '@PATIENT.DOB <= @INTERACTION."END"',
            expression:
              'FLOOR(DAYS_BETWEEN(@PATIENT.DOB,@INTERACTION."END") / 365)',
          },
          status: {
            name: "Vital Status",
            type: "text",
            defaultFilter: '@CODE.ATTRIBUTE = "VITALSTATUS"',
            expression: "@CODE.VALUE",
          },
          year: {
            name: "Year of Last Contact",
            type: "num",
            expression: 'YEAR(@INTERACTION."START")',
            defaultFilter: "",
          },
          calYear: {
            name: "Start Year",
            type: "num",
            expression: 'YEAR(@INTERACTION."START")',
            isDefault: true,
          },
          calMonth: {
            name: "Start Month",
            type: "num",
            expression: 'MONTH(@INTERACTION."START")',
            referenceFilter: '@REF.Catalog="HPH.MRI-MONTHS-CAT"',
            referenceExpression: "@REF.CODE",
            isDefault: true,
          },
          start: {
            name: "Start Date",
            type: "time",
            expression: '@INTERACTION."START"',
            isDefault: true,
          },
          end: {
            name: "End Date",
            type: "time",
            expression: '@INTERACTION."END"',
            isDefault: true,
          },
        },
      },
      ga_sample: {
        name: "Genome Sequencing",
        defaultFilter: '@INTERACTION.INTERACTION_TYPE = "Genomic"',
        order: 0,
        attributes: {
          sample_id: {
            name: "Sample Id",
            type: "text",
            defaultFilter: '@CODE.ATTRIBUTE = "SampleIndex"',
            expression: "@CODE.VALUE",
            order: 0,
            annotations: ["genomics_sample_id"],
          },
          reference_id: {
            name: "Genome Reference",
            type: "text",
            defaultFilter: '@CODE.ATTRIBUTE = "ReferenceGenome"',
            expression: "@CODE.VALUE",
            order: 1,
          },
          sample_class: {
            name: "Sample Class",
            type: "text",
            defaultFilter: '@CODE.ATTRIBUTE = "SampleClass"',
            expression: "@CODE.VALUE",
            order: 2,
          },
          calYear: {
            name: "Start Year",
            type: "num",
            expression: 'YEAR(@INTERACTION."START")',
            isDefault: true,
          },
          calMonth: {
            name: "Start Month",
            type: "num",
            expression: 'MONTH(@INTERACTION."START")',
            referenceFilter: '@REF.Catalog="HPH.MRI-MONTHS-CAT"',
            referenceExpression: "@REF.CODE",
            isDefault: true,
          },
          start: {
            name: "Start Date",
            type: "time",
            expression: '@INTERACTION."START"',
            isDefault: true,
          },
          end: {
            name: "End Date",
            type: "time",
            expression: '@INTERACTION."END"',
            isDefault: true,
          },
        },
      },
      ga_mutation: {
        name: "Genetic Variant",
        defaultFilter: "1=1",
        order: 8,
        from: {
          "@INTERACTION":
            '"legacy.genomics.db.models::MRI.VariantInteractions"',
        },
        attributes: {
          location: {
            name: "Location",
            type: "num",
            expression: "@INTERACTION.POSITION_START",
            order: 0,
            annotations: ["genomics_variant_location"],
            defaultFilter: "",
          },
          gene: {
            name: "Gene",
            type: "text",
            expression: "@INTERACTION.GENE_NAME",
            order: 1,
            defaultFilter: "",
          },
          region: {
            name: "Region",
            type: "text",
            expression: "@INTERACTION.REGION",
            order: 2,
            defaultFilter: "",
          },
          variant_type: {
            name: "Variant Type",
            type: "text",
            expression: "@INTERACTION.VARIANT_TYPE",
            order: 3,
            defaultFilter: "",
          },
          seq_alteration: {
            name: "Sequence Alteration",
            type: "text",
            expression: "@INTERACTION.SEQUENCE_ALTERATION",
            order: 4,
            defaultFilter: "",
          },
          aa_ref: {
            name: "Amino Acid Reference",
            type: "text",
            expression: "@INTERACTION.AA_REF",
            order: 5,
            defaultFilter: "",
          },
          aa_alt: {
            name: "Amino Acid",
            type: "text",
            expression: "@INTERACTION.AA_ALT",
            order: 6,
            defaultFilter: "",
          },
          calYear: {
            name: "Start Year",
            type: "num",
            expression: 'YEAR(@INTERACTION."START")',
            isDefault: true,
          },
          calMonth: {
            name: "Start Month",
            type: "num",
            expression: 'MONTH(@INTERACTION."START")',
            referenceFilter: '@REF.Catalog="HPH.MRI-MONTHS-CAT"',
            referenceExpression: "@REF.CODE",
            isDefault: true,
          },
          start: {
            name: "Start Date",
            type: "time",
            expression: '@INTERACTION."START"',
            isDefault: true,
          },
          end: {
            name: "End Date",
            type: "time",
            expression: '@INTERACTION."END"',
            isDefault: true,
          },
        },
      },
    },
    attributes: {
      pid: {
        name: "Patient ID",
        type: "text",
        expression: "@PATIENT.PATIENT_ID",
      },
      smoker: {
        name: "Smoker",
        type: "text",
        defaultFilter: '@OBS.OBS_TYPE = "SMOKER"',
        expression: "@OBS.OBS_CHAR_VAL",
        referenceFilter: '@REF.Catalog="HPH.MRI-YES-NO-CAT"',
        referenceExpression: "@REF.CODE",
      },
      pcount: {
        name: "Patient Count",
        type: "num",
        measureExpression: "COUNT(DISTINCT(@PATIENT.PATIENT_ID))",
      },
      nationality: {
        name: "Nationality",
        type: "text",
        expression: "@PATIENT.NATIONALITY",
      },
      cohort: {
        name: "Cohort",
        type: "text",
        defaultFilter: "@OBS.OBS_CHAR_VAL=@OBS.OBS_CHAR_VAL",
        expression: "@OBS.OBS_CHAR_VAL",
        from: {
          "@OBS": '"pa.db::CollectionsAsObservation"',
        },
      },
      firstName: {
        name: "First Name",
        type: "text",
        expression: "@PATIENT.FIRSTNAME",
      },
      lastName: {
        name: "Last Name",
        type: "text",
        expression: "@PATIENT.LASTNAME",
      },
      street: {
        name: "Street",
        type: "text",
        expression: "@PATIENT.STREET",
      },
      city: {
        name: "City",
        type: "text",
        expression: "@PATIENT.CITY",
      },
      zipcode: {
        name: "ZIP Code",
        type: "text",
        expression: "@PATIENT.POSTCODE",
      },
      region: {
        name: "Region",
        type: "text",
        expression: "@PATIENT.REGION",
      },
      country: {
        name: "Country",
        type: "text",
        expression: "@PATIENT.COUNTRY",
      },
      gender: {
        name: "Gender",
        type: "text",
        expression: "@PATIENT.GENDER",
        referenceFilter: '@REF.Catalog="HPH.MRI-GENDER-CAT"',
        referenceExpression: "@REF.Code",
      },
      monthOfBirth: {
        name: "Month of Birth",
        type: "num",
        expression: "MONTH(@PATIENT.DOB)",
      },
      yearOfBirth: {
        name: "Year of Birth",
        type: "num",
        expression: "YEAR(@PATIENT.DOB)",
      },
      dateOfBirth: {
        name: "Date of Birth",
        type: "time",
        expression: "@PATIENT.DOB",
      },
      dateOfDeath: {
        name: "Date of Death",
        type: "time",
        expression: "@PATIENT.DOD",
      },
      maritalStatus: {
        name: "Marital Status",
        type: "text",
        expression: "@PATIENT.MARITAL_STATUS",
      },
      title: {
        name: "Title",
        type: "text",
        expression: "@PATIENT.TITLE",
      },
      biomarker: {
        name: "Biomarker Type",
        type: "text",
        defaultFilter: '@OBS.OBS_TYPE = "BIOMARKER"',
        expression: "@OBS.OBS_CHAR_VAL",
      },
      packYearsSmoked: {
        name: "Pack-Years Smoked",
        type: "num",
        expression: "@OBS.OBS_NUM_VAL",
        defaultFilter: '@OBS.OBS_TYPE = "PACK_YEARS_SMOKED"',
      },
      smokingOnset: {
        name: "Smoking Onset Year",
        type: "num",
        expression: "@OBS.OBS_NUM_VAL",
        defaultFilter: '@OBS.OBS_TYPE = "SMOKING_ONSET"',
      },
      smokingOnsetAge: {
        name: "Smoking Onset Age",
        type: "num",
        expression: "@OBS.OBS_NUM_VAL",
        defaultFilter: '@OBS.OBS_TYPE = "SMOKING_ONSET_AGE"',
      },
      smokingStopped: {
        name: "Smoking Stopped Year",
        type: "num",
        expression: "@OBS.OBS_NUM_VAL",
        defaultFilter: '@OBS.OBS_TYPE = "SMOKING_STOPPED"',
      },
    },
  },
  chartOptions: {
    stacked: {
      enabled: true,
    },
    boxplot: {
      enabled: true,
    },
    km: {
      filter: [],
      enabled: true,
      confidenceInterval: 1.95996398454,
    },
    list: {
      enabled: true,
    },
    vb: {
      enabled: true,
      referenceName: "GRCh37",
    },
    minCohortSize: 1,
  },
};
