--liquibase formatted sql
--changeset alp:V1.0.0.0.4__create_study_data_cleanup_sp splitStatements:false

-------------------------------------------------------------------------------------------------
-- Purpose:
-- WARNING: THIS STORE PROCEDURE MUST NEVER BE USED IN PRODUCTION!!!!!!!!!
-- This is used to delete all study data which are processed by nifi via Study data pipeline
-- To use this Store Procedure, pass in the schema that the data flow has created in as a string parameter
-- SP Usage Example: CALL "SP::DELETE_STUDY_DATA_FROM_SCHEMA" ('STUDY_SCHEMA_1')
-------------------------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE "SP::DELETE_STUDY_DATA_FROM_SCHEMA" ("PARAM_SCHEMA" VARCHAR(100))
AS
BEGIN
	DECLARE DELETE_FROM_QUESTIONNAIRE_RESPONSE_SQL VARCHAR(500);
    DECLARE DELETE_FROM_RESEARCH_SUBJECT_SQL VARCHAR(500);
	DECLARE DELETE_FROM_OBSERVATION_SQL VARCHAR(500);
	DECLARE DELETE_FROM_PROVIDER_SQL VARCHAR(500);
    	DECLARE DELETE_FROM_PERSON_SQL VARCHAR(500);
    DECLARE DELETE_FROM_OMOP_TRACE_SQL VARCHAR(500);

	DELETE_FROM_QUESTIONNAIRE_RESPONSE_SQL =  'DELETE FROM "' || :PARAM_SCHEMA || '"."GDM.QUESTIONNAIRE_RESPONSE"';
	DELETE_FROM_RESEARCH_SUBJECT_SQL =  'DELETE FROM "' || :PARAM_SCHEMA || '"."GDM.RESEARCH_SUBJECT"';
	DELETE_FROM_OBSERVATION_SQL =  'DELETE FROM "' || :PARAM_SCHEMA || '"."OBSERVATION"';
	DELETE_FROM_PROVIDER_SQL =  'DELETE FROM "' || :PARAM_SCHEMA || '"."PROVIDER"';
	DELETE_FROM_PERSON_SQL =  'DELETE FROM "' || :PARAM_SCHEMA || '"."PERSON"';
	DELETE_FROM_OMOP_TRACE_SQL =  'DELETE FROM "' || :PARAM_SCHEMA || '"."OMOP.TRACE"';

	EXEC DELETE_FROM_QUESTIONNAIRE_RESPONSE_SQL;
	EXEC DELETE_FROM_RESEARCH_SUBJECT_SQL;
	EXEC DELETE_FROM_OBSERVATION_SQL;
	EXEC DELETE_FROM_PROVIDER_SQL;
	EXEC DELETE_FROM_PERSON_SQL;
	EXEC DELETE_FROM_OMOP_TRACE_SQL;
END;

--rollback DROP PROCEDURE "SP::DELETE_STUDY_DATA_FROM_SCHEMA";
