--liquibase formatted sql
--changeset alp:V1.0.0.0.1__create_drop_existing_sp_sp splitStatements:false
CREATE OR REPLACE PROCEDURE "SP::DROP_EXISTING_SP"("SP_NAME" VARCHAR(250))
AS
BEGIN
    DECLARE SP_EXISTS INTEGER;
    DECLARE DELETE_SP_SQL VARCHAR(500);

    SELECT COUNT(PROCEDURE_NAME) INTO SP_EXISTS FROM "SYS"."PROCEDURES"
    WHERE "SCHEMA_NAME" = 'TENANT_ADMIN_USER' AND "PROCEDURE_NAME" = :SP_NAME;

    IF :SP_EXISTS > 0 THEN
        DELETE_SP_SQL = 'DROP PROCEDURE "TENANT_ADMIN_USER"."' || :SP_NAME || '"';
        EXEC DELETE_SP_SQL;
    END IF;
END;

--rollback DROP PROCEDURE "SP::DROP_EXISTING_SP";