--liquibase formatted sql
--changeset alp:V1.0.0.0.0__create_s4h_data_cleanup_sp splitStatements:false

-------------------------------------------------------------------------------------------------
-- Purpose:
-- WARNING: THIS STORE PROCEDURE MUST NEVER BE USED IN PRODUCTION!!!!!!!!!
-- This is used to delete all Smart4Health data which are processed by nifi via Smart4Health data pipeline
-- To use this Store Procedure, pass in the schema that the data flow has created in as a string parameter
-- SP Usage Example: CALL "SP::DELETE_S4H_DATA_FROM_SCHEMA" ('SCHEMA_1')
-------------------------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE "SP::DELETE_S4H_DATA_FROM_SCHEMA" ("PARAM_SCHEMA" VARCHAR(100))
AS
BEGIN
	DECLARE DELETE_FROM_OMOP_PERSON_SQL VARCHAR(500);
	DECLARE DELETE_FROM_OMOP_OBSERVATION_SQL VARCHAR(500);
    DECLARE DELETE_FROM_OMOP_CONDITION_OCCURRENCE_SQL VARCHAR(500);
   	DECLARE DELETE_FROM_OMOP_PROCEDURE_OCCURRENCE_SQL VARCHAR(500);
    DECLARE DELETE_FROM_OMOP_DEVICE_EXPOSURE_SQL VARCHAR(500);
   	DECLARE DELETE_FROM_OMOP_VISIT_OCCURRENCE_SQL VARCHAR(500);
    DECLARE DELETE_FROM_OMOP_DRUG_EXPOSURE_SQL VARCHAR(500);
	DECLARE DELETE_FROM_GDM_CONSENT_SQL VARCHAR(500);
	DECLARE DELETE_FROM_GDM_QUESTIONNAIRE_RESPONSE_SQL VARCHAR(500);
	DECLARE DELETE_FROM_OMOP_TRACE_SQL VARCHAR(500);
	
   	DELETE_FROM_OMOP_PERSON_SQL = 'DELETE FROM "' || :PARAM_SCHEMA || '"."PERSON"';
	DELETE_FROM_OMOP_OBSERVATION_SQL = 'DELETE FROM "' || :PARAM_SCHEMA || '"."OBSERVATION"';
	DELETE_FROM_OMOP_CONDITION_OCCURRENCE_SQL = 'DELETE FROM "' || :PARAM_SCHEMA || '"."CONDITION_OCCURRENCE"';
	DELETE_FROM_OMOP_PROCEDURE_OCCURRENCE_SQL = 'DELETE FROM "' || :PARAM_SCHEMA || '"."PROCEDURE_OCCURRENCE"';
	DELETE_FROM_OMOP_DEVICE_EXPOSURE_SQL = 'DELETE FROM "' || :PARAM_SCHEMA || '"."DEVICE_EXPOSURE"';
	DELETE_FROM_OMOP_VISIT_OCCURRENCE_SQL = 'DELETE FROM "' || :PARAM_SCHEMA || '"."VISIT_OCCURRENCE"';
	DELETE_FROM_OMOP_DRUG_EXPOSURE_SQL = 'DELETE FROM "' || :PARAM_SCHEMA || '"."DRUG_EXPOSURE"';
	DELETE_FROM_GDM_CONSENT_SQL = 'DELETE FROM "' || :PARAM_SCHEMA || '"."GDM.CONSENT"';
	DELETE_FROM_GDM_QUESTIONNAIRE_RESPONSE_SQL = 'DELETE FROM "' || :PARAM_SCHEMA || '"."GDM.QUESTIONNAIRE_RESPONSE"';
	DELETE_FROM_OMOP_TRACE_SQL = 'DELETE FROM "' || :PARAM_SCHEMA || '"."OMOP.TRACE"';

	EXEC DELETE_FROM_OMOP_PERSON_SQL;
	EXEC DELETE_FROM_OMOP_OBSERVATION_SQL;
	EXEC DELETE_FROM_OMOP_CONDITION_OCCURRENCE_SQL;
	EXEC DELETE_FROM_OMOP_PROCEDURE_OCCURRENCE_SQL;
	EXEC DELETE_FROM_OMOP_DEVICE_EXPOSURE_SQL;
	EXEC DELETE_FROM_OMOP_VISIT_OCCURRENCE_SQL;
	EXEC DELETE_FROM_OMOP_DRUG_EXPOSURE_SQL;
	EXEC DELETE_FROM_GDM_CONSENT_SQL;
	EXEC DELETE_FROM_GDM_QUESTIONNAIRE_RESPONSE_SQL;
	EXEC DELETE_FROM_OMOP_TRACE_SQL;
END;

--rollback DROP PROCEDURE "SP::DELETE_S4H_DATA_FROM_SCHEMA";