--liquibase formatted sql
--changeset alp:V1.0.0.0.5__create_export_data_csv_sp splitStatements:false

CREATE OR REPLACE PROCEDURE "SP::EXPORT_DATA_FROM_SCHEMA" ("PATIENT_IDS" VARCHAR(4000), "SCHEMA_NAME" VARCHAR(127), "EXPORT_PATH" VARCHAR(2000))
AS
BEGIN

-------------------------------------------------------------------------------------------------
-- Purpose:
-- This is used to export dataset as csv's for each table matching specific patient ids to a path on the Hana instance. 
-- Then the files are exfiltrated using rsync/scp from the Hana instance.
-- SP Usage Example: CALL "SP::EXPORT_DATA_FROM_SCHEMA" ('182,1232,1232', 'CDMSYNPUF1K', '/tmp/synpuf1k')
-------------------------------------------------------------------------------------------------

	DECLARE EXPORT_TABLE_SQL VARCHAR(5000);
	DECLARE TEMP_EXPORT_TABLE_NAME VARCHAR(1000);
	DECLARE OBJECT_NAMES_OMOP VARCHAR(100) ARRAY = ARRAY('VIEW::OMOP.COND','VIEW::OMOP.COND_ERA','VIEW::OMOP.DEATH','VIEW::OMOP.DEVICE_EXPOSURE','VIEW::OMOP.DOSE_ERA','VIEW::OMOP.DRUG_ERA','VIEW::OMOP.DRUG_EXP','VIEW::OMOP.MEAS','VIEW::OMOP.OBS','VIEW::OMOP.OBS_PER','VIEW::OMOP.PATIENT','VIEW::OMOP.PP_PER','VIEW::OMOP.PROC','VIEW::OMOP.SPEC','VIEW::OMOP.VISIT');
	DECLARE OBJECT_NAMES_GDM VARCHAR(100) ARRAY = ARRAY('VIEW::GDM.CONSENT_BASE','VIEW::GDM.QUESTIONNAIRE_RESPONSE_BASE','VIEW::GDM.RESEARCH_SUBJECT_BASE');
	DECLARE i INT;
	DECLARE GENERATED_DATETIME VARCHAR(500);
	
	SELECT TO_VARCHAR (CURRENT_TIMESTAMP, 'YYYY_MM_DD_HH24_MI_SS') INTO GENERATED_DATETIME FROM DUMMY;
	
	FOR i in 1 .. CARDINALITY(:OBJECT_NAMES_OMOP) DO
	    TEMP_EXPORT_TABLE_NAME = :SCHEMA_NAME || '."EXPORT_' || :OBJECT_NAMES_OMOP[:i] || '_' || :GENERATED_DATETIME || '"';
	    EXPORT_TABLE_SQL = 'CREATE TABLE ' || :TEMP_EXPORT_TABLE_NAME || ' AS (SELECT * FROM ' || :SCHEMA_NAME || '."' || :OBJECT_NAMES_OMOP[:i] || '" WHERE PATIENT_ID IN (' || :PATIENT_IDS || '))';
	    EXEC EXPORT_TABLE_SQL;
	    EXPORT_TABLE_SQL = 'EXPORT ' || :TEMP_EXPORT_TABLE_NAME || ' AS CSV INTO ''' || :EXPORT_PATH || '''';
		EXEC EXPORT_TABLE_SQL;
		EXPORT_TABLE_SQL = 'DROP TABLE ' || :TEMP_EXPORT_TABLE_NAME;
		EXEC EXPORT_TABLE_SQL;
	END FOR;
		
	FOR i in 1 .. CARDINALITY(:OBJECT_NAMES_GDM) DO
		TEMP_EXPORT_TABLE_NAME = :SCHEMA_NAME || '."EXPORT_' || :OBJECT_NAMES_GDM[:i] || '_' || :GENERATED_DATETIME || '"';
	    EXPORT_TABLE_SQL = 'CREATE TABLE ' || :TEMP_EXPORT_TABLE_NAME || ' AS (SELECT * FROM ' || :SCHEMA_NAME || '."' || :OBJECT_NAMES_GDM[:i] || '" WHERE PERSON_ID IN (' || :PATIENT_IDS || '))';
	    EXEC EXPORT_TABLE_SQL;
	    EXPORT_TABLE_SQL = 'EXPORT ' || :TEMP_EXPORT_TABLE_NAME || ' AS CSV INTO ''' || :EXPORT_PATH || '''';
		EXEC EXPORT_TABLE_SQL;
		EXPORT_TABLE_SQL = 'DROP TABLE ' || :TEMP_EXPORT_TABLE_NAME;
		EXEC EXPORT_TABLE_SQL;
	END FOR;
END;

--rollback DROP PROCEDURE "SP::EXPORT_DATA_FROM_SCHEMA";
