version: "3"
services:
  db-credentials-mgr:
    build:
      context: .
      target: development
    # Mount our host directory to docker container
    # Reflect file changes from host to container
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn dev
