-- WHERE ETL_STARTED_AT < seconddate(unseconddate(${DATE_VALUE}))
INSERT INTO ${DESTINATION_SCHEMA}."GDM.QUESTIONNAIRE_RESPONSE" (SELECT * FROM ${SOURCE_SCHEMA}."GDM.QUESTIONNAIRE_RESPONSE" WHERE AUTHORED <= '${TIMESTAMP}');
INSERT INTO ${DESTINATION_SCHEMA}."GDM.ITEM" (
    SELECT * FROM ${SOURCE_SCHEMA}."GDM.ITEM" I WHERE I.GDM_QUESTIONNAIRE_RESPONSE_ID in (
        SELECT ID FROM ${SOURCE_SCHEMA}."GDM.QUESTIONNAIRE_RESPONSE" WHERE AUTHORED <= '${TIMESTAMP}'
    )
);
INSERT INTO ${DESTINATION_SCHEMA}."GDM.ANSWER" (
    SELECT * FROM ${SOURCE_SCHEMA}."GDM.ANSWER" J WHERE J.GDM_ITEM_ID IN (
        SELECT ID FROM ${SOURCE_SCHEMA}."GDM.ITEM" I WHERE I.GDM_QUESTIONNAIRE_RESPONSE_ID in (
        SELECT ID FROM ${SOURCE_SCHEMA}."GDM.QUESTIONNAIRE_RESPONSE" WHERE AUTHORED <= '${TIMESTAMP}'
        )
    )
);