apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "mri-pg-config-helm.secret" . }}
  labels:
    {{- include "mri-pg-config-helm.selectorLabels" . | nindent 4 }}
type: "Opaque"
data:
  PG__HOST: {{ .Values.secrets.POSTGRES_HOST | b64enc | quote }}
  PG__PORT: {{ .Values.secrets.POSTGRES_PORT | b64enc | quote }}
  PG__DB_NAME: {{ .Values.secrets.POSTGRES_DATABASE | b64enc | quote }}
  PG_SCHEMA: {{ .Values.secrets.POSTGRES_SCHEMA | b64enc | quote }}
  PG_USER: {{ .Values.secrets.POSTGRES_USER | b64enc | quote }}
  PG_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc | quote }}
  PG__MIN_POOL: {{ .Values.secrets.POSTGRES_MIN_POOL | b64enc | quote }}
  PG__MAX_POOL: {{ .Values.secrets.POSTGRES_MAX_POOL | b64enc | quote }}
  PG__DEBUG: {{ .Values.secrets.POSTGRES_DEBUG | b64enc | quote }}
  NODE_ENV: {{ .Values.secrets.NODE_ENV | b64enc | quote }}
  PG_CA_ROOT_CERT: {{ .Values.secrets.PG_CA_ROOT_CERT | b64enc | quote }}