curl 'http://localhost:5000/analytics-svc/api/services/patient/cohorts/compare/barchart?ids=f97ace1b-427f-471b-a8dd-5cf27b48a50f,ae29eb88-d8ef-4c75-ab1e-26b7b2a421b8&xaxis=patient.conditions.acme.interactions.radio.attributes.radio_ops,patient.conditions.acme.interactions.chemo.attributes.chemo_ops&yaxis=patient.attributes.monthOfBirth&configId=PatientAnalyticsInitialCI&configVersion=A' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, br' -H 'X-CSRF-Token: undefined' -H 'Accept-Language: en-US,en;q=0.9' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36' -H 'Accept: application/json, text/plain, */*' -H 'x-language: en-US' -H 'Cache-Control: no-cache' -H 'Referer: http://localhost:5000/' -H 'Cookie: xsSessionLanguage=en' -H 'Connection: keep-alive' --compressed


// curl 'http://localhost:5000/analytics-svc/api/services/patient/cohorts/compare/boxplot?ids=f97ace1b-427f-471b-a8dd-5cf27b48a50f,ae29eb88-d8ef-4c75-ab1e-26b7b2a421b8&xaxis=patient.conditions.acme.interactions.radio.attributes.radio_ops,patient.conditions.acme.interactions.chemo.attributes.chemo_ops&yaxis=patient.attributes.monthOfBirth&configId=PatientAnalyticsInitialCI&configVersion=A' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, br' -H 'X-CSRF-Token: undefined' -H 'Accept-Language: en-US,en;q=0.9' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36' -H 'Accept: application/json, text/plain, */*' -H 'x-language: en-US' -H 'Cache-Control: no-cache' -H 'Referer: http://localhost:5000/' -H 'Cookie: xsSessionLanguage=en' -H 'Connection: keep-alive' --compressed
