name: ALP nifi-mgmt-svc python library unit tests

on: [push]

jobs:
  test-alp-nifi-mgmt-svc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/checkout@v4
        with:
          repository:  ${{ vars.OVERRIDE_REPO }}
          token: ${{ secrets.CI_PAT }}
          path: 'tmp'
          sparse-checkout: 'alp-data-node-override'
          sparse-checkout-cone-mode: false
          ref: develop
  
      - shell: bash
        id: merge_files_from_override
        run: |
          cp -prvnl ./tmp/alp-data-node-override/* .

      - uses: actions/setup-python@v1
        name: Set up Python 3.7
        with:
          python-version: 3.7
      - name: Run unit tests
        run: |
          cd services/alp-nifi-mgmt-svc/py_nifi_modules
          pip install -r requirements-dev.txt
          python3 -m pytest
