services:

  alp-cube:
    container_name: alp-minerva-cube-${BASE_PORT:-1}
    depends_on:
      alp-logto:
        condition: service_healthy
      alp-minerva-postgres:
        condition: service_healthy
    image: alpcr.azurecr.io/alp-data-node/alp-cube:${DOCKER_TAG_NAME:-develop}
    labels:
      com.clinical-research.description: alp-cube
    networks:
      - alp
    platform: linux/amd64
    profiles:
      - cube
    environment:
      CUBEJS_DB_HOST: ${PG_HOST:-alp-minerva-postgres-1}
      CUBEJS_DB_NAME: ${PG_DB_NAME:-alp}
      CUBEJS_DB_PASS: ${PG_ADMIN_PASSWORD}
      CUBEJS_DB_PORT: ${PG_PORT:-5432}
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_USER: ${PG_ADMIN_USER:-alp_pg_admin_user}
      CUBEJS_DEV_MODE: true
      CUBEJS_LOG_LEVEL: trace
      CUBEJS_SCHEMA_PATH: model
