apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alp-pg-management.fullname" . }}-automate
  labels:
    {{- include "alp-pg-management.labels" . | nindent 4 }}
data:
    NODE_ENV: {{ .Values.env.NODE_ENV | quote }}