apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "alp-pg-management.fullname" . }}-fhir
  labels:
    {{- include "alp-pg-management.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "alp-pg-management.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-db-setup
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ tpl .Values.env.image.repository . }}/alp-pg-management:{{ tpl .Values.env.image.tag . }}"
          imagePullPolicy: {{ .Values.env.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "alp-pg-management.fullname" . }}-automate
          volumeMounts:
          - name: alp-pg-management-volume
            mountPath: "/var/alp-pg-management"
            readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Never
      volumes:
        - name: alp-pg-management-volume
          secret:
            secretName: {{ include "alp-pg-management.fullname" . }}-automate