apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "alp-pg-management.fullname" . }}-automate
  labels:
    {{- include "alp-pg-management.selectorLabels" . | nindent 4 }}
type: "Opaque"
stringData:
  POSTGRES_CONNECTION_CONFIG: {{ .Values.secrets.POSTGRES_CONNECTION_CONFIG  | quote }}
  POSTGRES_SUPERUSER: {{ .Values.secrets.POSTGRES_SUPERUSER  | quote }}
  POSTGRES_SUPERUSER_PASSWORD: {{ .Values.secrets.POSTGRES_SUPERUSER_PASSWORD  | quote }}
  POSTGRES_MANAGE_USERS: {{ .Values.secrets.POSTGRES_MANAGE_USERS  | quote }}
  POSTGRES_MANAGE_CONFIG: {{ .Values.secrets.POSTGRES_MANAGE_CONFIG  | quote }}