hub:
  extraEnv:
    OAUTH_CALLBACK_URL: https://alp-staging.alp-dev.org/jhub/hub/oauth_callback
    OAUTH2_AUTHORIZE_URL: https://alpsgb2c.b2clogin.com/alpsgb2c.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1a_signin_resetpassword
    OAUTH2_TOKEN_URL: https://alpsgb2c.b2clogin.com/alpsgb2c.onmicrosoft.com/oauth2/v2.0/token?p=b2c_1a_signin_resetpassword
    OAUTH2_USERDATA_URL: https://login.microsoftonline.com/f6e2e3de-5a60-449c-baff-5e9643e8412e/openid/userinfo
    AAD_TENANT_ID: "f6e2e3de-5a60-449c-baff-5e9643e8412e"
  extraConfig:
    jupyterlab: |
      #c.Spawner.cmd = ['jupyter-labhub']
      c.JupyterHub.authenticate_prometheus = False
  db:
    #type: sqlite-memory
    pvc:
      storageClassName: csi-rbd-sc
  baseUrl: /jhub
  service:
    annotations:
      prometheus.io/path: "/jhub/hub/metrics"
      prometheus.io/scrape: "true"

auth:
  type: custom
  state:
    enabled: true
  admin:
    access: true
    users:

prePuller:
  continuous:
    enabled: false

singleuser:
  image:
    azureCR:
      tag: 'latest'
    d4lNexus:
      tag: 'latest'
  extraEnv:
    PYQE_JWT_AUDIENCE: ""
    PYQE_AZUREADB2C_CLIENT_ID: ""

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/whitelist-source-range: "194.246.32.0/22,192.168.28.0/24,192.168.89.0/24,192.168.90.0/24,100.65.0.0/24"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "content-security-policy: default-src 'self'; frame-src 'self' blob:; img-src 'self' data:; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src https: wss:; object-src 'self' blob:; report-uri /jhub/hub/security/csp-report";
  hosts:
    - alp-staging.alp-dev.org
  tls:
    - hosts:
      - alp-staging.alp-dev.org
      secretName: tls-alp-dev.org

custom:
  hostname: "alp-staging.alp-dev.org"