FROM node:14.19.3-alpine

#ARG
#GIT COMMIT Passed during docker build time
ARG GIT_COMMIT_ARG

#ENV
ENV GIT_COMMIT=$GIT_COMMIT_ARG

USER root

RUN apk add --update --upgrade bash curl openssl zlib

ADD alp-data-node-override/services/alp-jupyterhub/jupyternb-single-user/researcher-files-backup/rclone-*-linux-amd64.zip .

RUN unzip ./rclone-current-linux-amd64.zip && \
	cp ./rclone-*-linux-amd64/rclone /usr/bin/ && \
	chmod 755 /usr/bin/rclone

RUN addgroup -S alp -g 3000 && adduser --uid 3000 -S docker -G alp

USER docker

WORKDIR /home/docker

RUN npm install chokidar

ADD alp-jupyterhub/jupyternb-single-user/researcher-files-backup/bootstrap-backup.sh .
ADD alp-jupyterhub/jupyternb-single-user/researcher-files-backup/researcher-files-backup.js .

USER root

RUN rm -rf /usr/local/lib/node_modules/npm

USER docker

CMD ["bash", "bootstrap-backup.sh"]