server:
  port: 10500
  error:
    include-message: always
  servlet:
    context-path: /files-manager
spring:
  application:
    name: Files Manager
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  datasource:
    url: jdbc:postgresql://${PG__HOST}:${PG__PORT}/${PG__DB_NAME}?currentSchema=files_manager
    username: ${PG_ADMIN_USER}
    password: ${PG_ADMIN_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: files_manager
    hibernate:
      ddl-auto: update
    show-sql: false


