###
# Set response header "Username" from the decoded token
GET https://localhost:41100/usermgmt/api/me/is_token_valid_internal
Authorization: Bearer eyJhbGciOiJFUzM4NCIsInR5cCI6ImF0K2p3dCIsImtpZCI6ImN0SEpPZmM1S3RtaWNKRndaXy1SeUF6SkpzbjFXSDRVUnZPZms2NUhfaGcifQ.eyJqdGkiOiJSQktZdEpiTk5TZEZhc2QweGNDWDkiLCJzdWIiOiJuY2R0dnJnNTlncDIiLCJpYXQiOjE3MjExOTU5OTcsImV4cCI6MTcyMTE5OTU5Nywic2NvcGUiOiJyb2xlLnN5c3RlbWFkbWluIHJvbGUudGVuYW50dmlld2VyIHJvbGUudXNlcmFkbWluIiwiY2xpZW50X2lkIjoiYmxmd2xrYmd2bHZvZHVlODZhbzRlIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDExMDAvb2lkYyIsImF1ZCI6Imh0dHBzOi8vYWxwLWRlZmF1bHQifQ.IpXLfL5Rp-s-tqaVETpNZvtWe3QNReYZchWjny8UKJnKkBrdvD3ni6zHt66WpGq-BzlkYvju6ZlL5nYvWq8m9jcR6rWZ73zQCW6KU2KxLFVkTRDHa849TaglAF7R9j5T

###
# Verify perseus API endpoint with D2E token (For 401, replace with valid token)
GET http://localhost:41180/backend/api/get_cdm_versions
Authorization: Bearer eyJhbGciOiJFUzM4NCIsInR5cCI6ImF0K2p3dCIsImtpZCI6ImN0SEpPZmM1S3RtaWNKRndaXy1SeUF6SkpzbjFXSDRVUnZPZms2NUhfaGcifQ.eyJqdGkiOiJFQWN0VWZMVUx1eFJxV3JMWGcteWgiLCJzdWIiOiI2eG0yamxoeXh1OHkiLCJpYXQiOjE3MjEyMDEyMzUsImV4cCI6MTcyMTIwNDgzNSwic2NvcGUiOiIiLCJjbGllbnRfaWQiOiJibGZ3bGtiZ3Zsdm9kdWU4NmFvNGUiLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0MTEwMC9vaWRjIiwiYXVkIjoiaHR0cHM6Ly9hbHAtZGVmYXVsdCJ9.KlGdQNrtp_q8f4q_0IZG9rBcI_ds97abyKhWwq8AgGxn9u0JMEnjoHZAgZGHS3kR-RzctFznBSeecyC1J7AFGhRIZECJ3WzqXv7SDwaRRrGkT6p08Ww268S7uwZO2QrX

###
# Verify perseus API endpoint with perseus token (For 401, replace with valid token)
GET http://localhost:41180/backend/api/get_cdm_versions
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwZXJzZXVzIiwiZXhwIjoxNzIxMjM5MzkyLCJpYXQiOjE3MjExOTYxOTJ9.kf58UbVY6jg9kQwasypbmOfCjEDwjzUqMFDpb5QsZ0g

