version: "3"
services:
  portal-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    # Mount our host directory to docker container
    # Reflect file changes from host to container
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:debug
    ports:
      - 9225:9225
