export const INDEX_ATTRIBUTES = {
  concept: {
    conceptId: 'concept_id',
    conceptName: 'concept_name',
    domainId: 'domain_id',
    vocabularyId: 'vocabulary_id',
    conceptClassId: 'concept_class_id',
    standardConcept: 'standard_concept',
    conceptCode: 'concept_code',
    validStartDate: 'valid_start_date',
    validEndDate: 'valid_end_date',
    invalidReason: 'invalid_reason',
  },
  concept_relationship: {
    meilisearchId: 'meilisearch_id',
    conceptId1: 'concept_id_1',
    conceptId2: 'concept_id_2',
    relationshipId: 'relationship_id',
    validStartDate: 'valid_start_date',
    validEndDate: 'valid_end_date',
    invalidReason: 'invalid_reason',
  },
  relationship: {
    meilisearchId: 'meilisearch_id',
    relationshipId: 'relationship_id',
    relationshipName: 'relationship_name',
    isHierarchical: 'is_hierarchical',
    definesAncestry: 'defines_ancestry',
    reverseRelationshipId: 'reverse_relationship_id',
    relationshipConceptId: 'relationship_concept_id',
  },
  vocabulary: {
    meilisearchId: 'meilisearch_id',
    vocabularyId: 'vocabulary_id',
    vocabularyName: 'vocabulary_name',
    vocabularyReference: 'vocabulary_reference',
    vocabularyVersion: 'vocabulary_version',
    vocabularyConceptId: 'vocabulary_concept_id',
  },
  concept_synonym: {
    meilisearchId: 'meilisearch_id',
    conceptId: 'concept_id',
    conceptSynonymName: 'concept_synonym_name',
    languageConceptId: 'language_concept_id',
  },
  concept_class: {
    meilisearchId: 'meilisearch_id',
    conceptClassId: 'concept_class_id',
    conceptClassName: 'concept_class_name',
    conceptClassConceptId: 'concept_class_concept_id',
  },
  domain: {
    meilisearchId: 'meilisearch_id',
    domainId: 'domain_id',
    domainName: 'domain_name',
    domainConceptId: 'domain_concept_id',
  },
  concept_ancestor: {
    meilisearchId: 'meilisearch_id',
    ancestorConceptId: 'ancestor_concept_id',
    descendantConceptId: 'descendant_concept_id',
    minLevelsOfSeparation: 'min_levels_of_separation',
    maxLevelsOfSeparation: 'max_levels_of_separation',
  },
  concept_recommended: {
    conceptId1: 'concept_id_1',
    conceptId2: 'concept_id_2',
    relationshipId: 'relationship_id',
  },
} as const;

// TODO: SKIP_DUCKDB_FILTER_OPTIONS_QUERY to be removed once frontend issue of sending multiple api calls upon concepts screen loading is fixed
// https://github.com/alp-os/internal/issues/1070
export const DUMMY_FILTER_OPTIONS_FACETS = {
  conceptClassId: {
    '10th level': 0,
    '11-digit NDC': 0,
    '11th level': 0,
    '12th level': 0,
    '2-dig nonbill code': 0,
    '2nd level': 0,
    '3-char billing code': 0,
    '3-char nonbill code': 0,
    '3-dig billing code': 0,
    '3-dig billing E code': 0,
    '3-dig billing V code': 0,
    '3-dig nonbill code': 0,
    '3-dig nonbill E code': 0,
    '3-dig nonbill V code': 0,
    '3rd level': 0,
    '4-char billing code': 0,
    '4-char nonbill code': 0,
    '4-dig billing code': 0,
    '4-dig billing E code': 0,
    '4-dig billing V code': 0,
    '4-dig nonbill code': 0,
    '4-dig nonbill V code': 0,
    '4th level': 0,
    '5-char billing code': 0,
    '5-char nonbill code': 0,
    '5-dig billing code': 0,
    '5-dig billing V code': 0,
    '5th level': 0,
    '6-char billing code': 0,
    '6-char nonbill code': 0,
    '6th level': 0,
    '7-char billing code': 0,
    '7th level': 0,
    '8th level': 0,
    '9-digit NDC': 0,
    '9th level': 0,
    'Admin Concept': 0,
    'Animal Drug': 0,
    Answer: 0,
    'ATC 1st': 0,
    'ATC 2nd': 0,
    'ATC 3rd': 0,
    'ATC 4th': 0,
    'ATC 5th': 0,
    Attribute: 0,
    Benefit: 0,
    'Biological Function': 0,
    'Body Structure': 0,
    'Brand Name': 0,
    'Branded Dose Group': 0,
    'Branded Drug': 0,
    'Branded Drug Box': 0,
    'Branded Drug Comp': 0,
    'Branded Drug Form': 0,
    'Branded Pack': 0,
    'Branded Pack Box': 0,
    'Canonical Unit': 0,
    CDM: 0,
    'Cellular Therapy': 0,
    'Claims Attachment': 0,
    'Clinical Dose Group': 0,
    'Clinical Drug': 0,
    'Clinical Drug Box': 0,
    'Clinical Drug Comp': 0,
    'Clinical Drug Form': 0,
    'Clinical Finding': 0,
    'Clinical Observation': 0,
    'Clinical Pack': 0,
    'Clinical Pack Box': 0,
    'Concept Class': 0,
    'Condition Status': 0,
    'Condition Type': 0,
    'Context-dependent': 0,
    Cosmetic: 0,
    'Cost Type': 0,
    Currency: 0,
    'Death Type': 0,
    Detail: 0,
    Device: 0,
    'Device Type': 0,
    'Disease Dynamic': 0,
    'Disease Extent': 0,
    Disposition: 0,
    'Doc Kind': 0,
    'Doc Role': 0,
    'Doc Setting': 0,
    'Doc Subject Matter': 0,
    'Doc Type of Service': 0,
    Domain: 0,
    'Dose Form': 0,
    'Dose Form Group': 0,
    'Drug Type': 0,
    'Episode of Care': 0,
    Ethnicity: 0,
    Event: 0,
    Field: 0,
    Food: 0,
    Gender: 0,
    HCPCS: 0,
    'HCPCS Class': 0,
    'HCPCS Modifier': 0,
    'ICD9CM code': 0,
    'Inactive Concept': 0,
    Ingredient: 0,
    'Lab Test': 0,
    Language: 0,
    'Linkage Assertion': 0,
    'Linkage Concept': 0,
    Location: 0,
    'LOINC Class': 0,
    'LOINC Component': 0,
    'LOINC Document Type': 0,
    'LOINC Group': 0,
    'LOINC Hierarchy': 0,
    'LOINC Method': 0,
    'LOINC Property': 0,
    'LOINC Scale': 0,
    'LOINC System': 0,
    'LOINC Time': 0,
    'Marketed Product': 0,
    'Meas Type': 0,
    Metadata: 0,
    'Metal level': 0,
    'Model Comp': 0,
    'Morph Abnormality': 0,
    'Multiple Ingredients': 0,
    'Namespace Concept': 0,
    'Navi Concept': 0,
    'Non-Stand Allergenic': 0,
    'Note Type': 0,
    'Obs Period Type': 0,
    'Observable Entity': 0,
    Observation: 0,
    'Observation Type': 0,
    Organism: 0,
    'OTC Drug': 0,
    'Patient Status': 0,
    Payer: 0,
    'Pharma/Biol Product': 0,
    'Physical Force': 0,
    'Physical Object': 0,
    'Physician Specialty': 0,
    'Plan Stop Reason': 0,
    'Plasma Derivative': 0,
    'Precise Ingredient': 0,
    'Precoordinated pair': 0,
    'Prescription Drug': 0,
    Procedure: 0,
    'Procedure Type': 0,
    Provider: 0,
    'Qualifier Value': 0,
    'Quant Branded Box': 0,
    'Quant Branded Drug': 0,
    'Quant Clinical Box': 0,
    'Quant Clinical Drug': 0,
    Race: 0,
    'Record Artifact': 0,
    Relationship: 0,
    'Revenue Code': 0,
    'Social Context': 0,
    'Special Concept': 0,
    Specimen: 0,
    SPL: 0,
    Sponsor: 0,
    'Staging / Scales': 0,
    'Standard Allergenic': 0,
    Substance: 0,
    Summary: 0,
    Supplement: 0,
    Supplier: 0,
    Survey: 0,
    Table: 0,
    Treatment: 0,
    'Type Concept': 0,
    'UB04 Point of Origin': 0,
    'UB04 Pri Typ of Adm': 0,
    'UB04 Pt dis status': 0,
    Undefined: 0,
    Unit: 0,
    'US Census Division': 0,
    'US Census Region': 0,
    Vaccine: 0,
    Visit: 0,
    'Visit Type': 0,
    Vocabulary: 0,
  },
  domainId: {
    Condition: 0,
    'Condition Status': 0,
    'Condition/Device': 0,
    'Condition/Meas': 0,
    Cost: 0,
    Currency: 0,
    Device: 0,
    Drug: 0,
    Episode: 0,
    Ethnicity: 0,
    Gender: 0,
    Geography: 0,
    Language: 0,
    'Meas Value': 0,
    'Meas Value Operator': 0,
    Measurement: 0,
    Metadata: 0,
    Note: 0,
    Observation: 0,
    Payer: 0,
    Plan: 0,
    'Plan Stop Reason': 0,
    Procedure: 0,
    Provider: 0,
    Race: 0,
    Relationship: 0,
    'Revenue Code': 0,
    Route: 0,
    'Spec Anatomic Site': 0,
    'Spec Disease Status': 0,
    Specimen: 0,
    Sponsor: 0,
    'Type Concept': 0,
    Unit: 0,
    Visit: 0,
  },
  standardConcept: {
    C: 0,
    S: 0,
  },
  vocabularyId: {
    ABMS: 0,
    ATC: 0,
    CDM: 0,
    'CMS Place of Service': 0,
    'Concept Class': 0,
    'Condition Status': 0,
    'Condition Type': 0,
    Cost: 0,
    'Cost Type': 0,
    Currency: 0,
    'Death Type': 0,
    'Device Type': 0,
    Domain: 0,
    'Drug Type': 0,
    Episode: 0,
    Ethnicity: 0,
    Gender: 0,
    HCPCS: 0,
    ICD10CM: 0,
    ICD9CM: 0,
    ICD9Proc: 0,
    'Korean Revenue Code': 0,
    Language: 0,
    LOINC: 0,
    'Meas Type': 0,
    'Medicare Specialty': 0,
    Metadata: 0,
    NDC: 0,
    None: 0,
    'Note Type': 0,
    NUCC: 0,
    'Obs Period Type': 0,
    'Observation Type': 0,
    'OMOP Extension': 0,
    OSM: 0,
    Plan: 0,
    'Plan Stop Reason': 0,
    'Procedure Type': 0,
    Race: 0,
    Relationship: 0,
    'Revenue Code': 0,
    RxNorm: 0,
    'RxNorm Extension': 0,
    SNOMED: 0,
    SOPT: 0,
    SPL: 0,
    Sponsor: 0,
    'Type Concept': 0,
    'UB04 Point of Origin': 0,
    'UB04 Pri Typ of Adm': 0,
    'UB04 Pt dis status': 0,
    'UB04 Typ bill': 0,
    UCUM: 0,
    'US Census': 0,
    Visit: 0,
    'Visit Type': 0,
    Vocabulary: 0,
  },
  validity: {
    Valid: 0,
    Invalid: 0,
  },
  concept: {
    Standard: 0,
    'Non-standard': 0,
  },
};
