{{- if and .Values.singleuser.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: singleuser
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- $_ := merge (dict "componentLabel" "singleuser-server") . }}
      {{- include "jupyterhub.matchLabels" $_ | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            hub.jupyter.org/network-access-hub: "true"
            component: "proxy"
      - podSelector:
          matchLabels:
            hub.jupyter.org/network-access-proxy-api: "true"
            hub.jupyter.org/network-access-proxy-http: "true"
            hub.jupyter.org/network-access-singleuser: "true"
            component: "hub"
      ports:
        - protocol: TCP
          port: 8888
    {{- /* Useful if you want to give user server access to pods from other namespaces */}}
    {{- if .Values.singleuser.networkPolicy.ingress }}
    {{- .Values.singleuser.networkPolicy.ingress | toYaml | trimSuffix "\n" | nindent 4 }}
    {{- end }}
  egress:
      - to:
        - podSelector:
            matchLabels:
              hub.jupyter.org/network-access-proxy-api: "true"
              hub.jupyter.org/network-access-proxy-http: "true"
              hub.jupyter.org/network-access-singleuser: "true"
              component: "hub"
        ports: #  HTTP. Will change when ssl is enabled
        - port: 8081
      - to:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.custom.defaultK8sNamespace }}
          podSelector:
            matchLabels:
              app.kubernetes.io/instance: "alp-data"
        ports:
          - port: 5001
      - to:
        - namespaceSelector:
            matchLabels:
              name: "kube-system"
          podSelector:
              matchLabels:
                k8s-app: "kube-dns"
        ports:
        - port: 53 #DNS
          protocol: TCP
        - port: 53 #DNS
          protocol: UDP
      - ports: # For swift storage portal.{fra1,ber1}.alp-dev.org
        - port: 5000
          protocol: TCP
        - port: 8080
          protocol: TCP
        to:
        - ipBlock:
            cidr: 192.168.120.10/32
        - ipBlock:
            cidr: 192.168.26.10/32
      - ports:
        - port: 443
        to: #Added "git" from the official https://api.github.com/meta
        - ipBlock:
            cidr: 192.30.252.0/22
        - ipBlock:
            cidr: 185.199.108.0/22
        - ipBlock:
            cidr: 140.82.112.0/20
        - ipBlock:
            cidr: 143.55.64.0/20
        - ipBlock:
            cidr: 13.114.40.48/32
        - ipBlock:
            cidr: 52.192.72.89/32
        - ipBlock:
            cidr: 52.69.186.44/32
        - ipBlock:
            cidr: 15.164.81.167/32
        - ipBlock:
            cidr: 52.78.231.108/32
        - ipBlock:
            cidr: 13.234.176.102/32
        - ipBlock:
            cidr: 13.234.210.38/32
        - ipBlock:
            cidr: 13.229.188.59/32
        - ipBlock:
            cidr: 13.250.177.223/32
        - ipBlock:
            cidr: 52.74.223.119/32
        - ipBlock:
            cidr: 13.236.229.21/32
        - ipBlock:
            cidr: 13.237.44.5/32
        - ipBlock:
            cidr: 52.64.108.95/32
        - ipBlock:
            cidr: 18.228.52.138/32
        - ipBlock:
            cidr: 18.228.67.229/32
        - ipBlock:
            cidr: 18.231.5.6/32
        - ipBlock:
            cidr: 18.181.13.223/32
        - ipBlock:
            cidr: 54.238.117.237/32
        - ipBlock:
            cidr: 54.168.17.15/32
        - ipBlock:
            cidr: 3.34.26.58/32
        - ipBlock:
            cidr: 13.125.114.27/32
        - ipBlock:
            cidr: 3.7.2.84/32
        - ipBlock:
            cidr: 3.6.106.81/32
        - ipBlock:
            cidr: 18.140.96.234/32
        - ipBlock:
            cidr: 18.141.90.153/32
        - ipBlock:
            cidr: 18.138.202.180/32
        - ipBlock:
            cidr: 52.63.152.235/32
        - ipBlock:
            cidr: 3.105.147.174/32
        - ipBlock:
            cidr: 3.106.158.203/32
        - ipBlock:
            cidr: 54.233.131.104/32
        - ipBlock:
            cidr: 18.231.104.233/32
        - ipBlock:
            cidr: 18.228.167.86/32
    {{- if .Values.singleuser.networkPolicy.egress }}
    {{- .Values.singleuser.networkPolicy.egress | toYaml | trimSuffix "\n" | nindent 4 }}
    {{- end }}
{{- end }}
