swagger: "2.0"
info:
  version: "Query Svc 1.0"
  title: Clinical Research
  description: .

basePath: /analytics-svc/api/services/query

schemes:
  - http
  - https
produces:
  - application/json
paths:
  /:
    x-swagger-router-controller: query
    post:
      description: create query
      operationId: generateQuery
      consumes:
        - application/json
      parameters:
        - name: queryParams
          in: body
          description: all query parameters (i.e.configId, configVersion, studyId, queryType, language, ifrRequest)
          required: true
          schema:
            type: object
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/QueryGenResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /cohort:
    x-swagger-router-controller: cohort
    post:
      description: create cohort related queries
      operationId: generateQuery
      consumes:
        - application/json
      parameters:
        - name: queryParams
          in: body
          description: all query parameters (i.e.configId, configVersion, studyId, queryType, language, ifrRequest)
          required: true
          schema:
            type: object
      responses:
        "200":
          description: Success
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /cohortCompare:
    x-swagger-router-controller: cohortCompareQuery
    post: 
      description: create list of bookmark cohort queries 
      operationId: generateQuery
      consumes:
          - application/json
      parameters:
          - name: queryParams
            in: body
            description: all query parameters (i.e. attributePath, configParams)
            required: true
            schema:
              type: object
      responses:
          "200":
            description: Success
          default:
              description: Error
              schema:
                $ref: "#/definitions/Error"
  /domainvalues:
    x-swagger-router-controller: domainValuesQuery
    post:
      description: create domain values query
      operationId: generateQuery
      consumes:
        - application/json
      parameters:
        - name: queryParams
          in: body
          description: all query parameters (i.e. attributePath, configParams)
          required: true
          schema:
            type: object
      responses:
        "200":
          description: Success
        default:
            description: Error
            schema:
              $ref: "#/definitions/Error"
  /pluginendpoint:
    x-swagger-router-controller: pluginEndpointQuery
    post:
      description: create plugin endpoint query
      operationId: generateQuery
      consumes:
        - application/json
      parameters:
        - name: queryParams
          in: body
          description: all query parameters (i.e. config, querySelector)
          required: true
          schema:
            type: object
      responses:
        "200":
          description: Success
        default:
            description: Error
            schema:
              $ref: "#/definitions/Error"
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  QueryGenResponse:
    type: object
    description: query generation svc response
    properties:
      queryObject:
        type: object
        description: query object representing the query
      fast:
        type: object
        description: serialized fast object
      config:
        type: object
        description: config used for query generation
      measures:
        type: object
        description: measures of queries
      categories:
        type: object
        description: categories of queries
      groupAttrAliases:
        type: object
        description: group Attr Aliases of queries
      cdmConfigMetaData:
        type: object
        description: cdm Config Meta Data  of queries
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string