name: ALP DB Credentials unit tests

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches:
      - develop
jobs:
  test-alp-db-credentials:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: dorny/paths-filter@v2
      id: check_file_changed
      with:
        filters: |
          db_credentials_changed:
            - 'services/alp-db-credentials/**'
    - name: Setup node if files have changed
      uses: actions/setup-node@v3
      if: github.ref_name == 'develop' || steps.check_file_changed.outputs.db_credentials_changed == 'True'
      with:
        node-version: '18.14.0'
    # Run the step only with "db_credentials_changed" equals "True"
    - name: Run unit tests if files have changed
      if: github.ref_name == 'develop' || steps.check_file_changed.outputs.db_credentials_changed == 'True'
      run: |
        cd services/alp-db-credentials
        yarn --prefer-offline
        yarn build:lint
        yarn test
