name: ALP Portal Server unit tests

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  test-alp-portal-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3.0.2
        id: check_file_changed
        with:
          filters: |
            portal_server_changed:
              - 'services/alp-portal-server/**'

      - name: Setup node if files have changed
        uses: actions/setup-node@v4
        if: env.BRANCH_NAME == 'develop' || steps.check_file_changed.outputs.portal_server_changed == 'True'
        with:
          node-version: "18.20.4"
      # Run the step only with "portal_server_changed" equals "True"

      - name: Run unit tests if files have changed
        if: env.BRANCH_NAME == 'develop' || steps.check_file_changed.outputs.portal_server_changed == 'True'
        run: |
          cd services/alp-portal-server
          yarn --prefer-offline
          yarn build:lint
          yarn test
