name: Cachedb tests

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  test-cachedb:
    runs-on: ubuntu-22.04
    env:
      LOCAL_DEBUG: "true"
      SERVICE_ROUTES: '{"portalServer": "dummy", "usermgmt": "dummy", "idIssuerUrl": "dummy"}'
      DUCKDB_EXTENSIONS_FOLDER: "/home/runner/work/d2e/d2e/services/cachedb/duckdb_extensions"
    steps:
    - uses: actions/checkout@v4

    - name: Create folder to store duckdb extensions for offline plugins
      run: |
        mkdir $DUCKDB_EXTENSIONS_FOLDER

    - uses: dorny/paths-filter@v3.0.2
      id: check_file_changed
      with:
        filters: |
          cachedb_changed:
            - 'services/cachedb/**'
            
    - name: Setup python if files have changed
      uses: actions/setup-python@v2
      if: env.BRANCH_NAME == 'develop' || steps.check_file_changed.outputs.cachedb_changed == 'True'
      with:
        python-version: 3.11.1
        cache: 'pip'
  
    - name: Install pip packages if files have changed
      if: env.BRANCH_NAME == 'develop' || steps.check_file_changed.outputs.cachedb_changed == 'True'
      working-directory: ./services/cachedb
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    # Create folder to store duckdb extensions for offline plugins
    - name: Install duckdb extensions for offline use if files have changed
      env: 
        DUCKDB_VERSION: 1.1.1 # version must match duckdb in requirements.txt
      if: env.BRANCH_NAME == 'develop' || steps.check_file_changed.outputs.cachedb_changed == 'True'
      working-directory: ./services/cachedb/duckdb_extensions
      run: |
        wget https://extensions.duckdb.org/v$DUCKDB_VERSION/linux_amd64_gcc4/postgres_scanner.duckdb_extension.gz && 
        wget https://extensions.duckdb.org/v$DUCKDB_VERSION/linux_amd64_gcc4/fts.duckdb_extension.gz && 
        gzip -d postgres_scanner.duckdb_extension.gz && 
        gzip -d fts.duckdb_extension.gz

    - name: Run unit tests if files have changed
      if: env.BRANCH_NAME == 'develop' || steps.check_file_changed.outputs.cachedb_changed == 'True'
      working-directory: ./services/cachedb/src
      run: PYTHON_ENV=TEST python3 -m pytest -v --disable-pytest-warnings