name: DC Deploy GitHub Agent

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  DOCKER_TAG_NAME: ${{ github.sha }}
  ENV_NAME: local
  ENV_TYPE: local
  GIT_COMMIT_ARG: ${{ github.sha }}
  D2E_RESOURCE_LIMIT: 1 # Use all the resources for GHA

# Run only one job per branch
concurrency:
  group: ${{ github.head_ref || github.ref_name }}-docker-compose-up # Run the latest push
  cancel-in-progress: true # Cancel in progress jobs of the workflow of the branch

jobs:
  docker-compose-up:
    runs-on: ubuntu-latest # Custom runner 4 cpus & 14gb ram

    if: (github.ref_name == 'develop' || contains('rc-', github.ref_name) || github.event_name == 'workflow_dispatch') || ( github.event_name == 'pull_request' && !github.event.pull_request.draft ) # Should run if branch is develop/rc/workflow_dispatch and doesnt have a PR
    steps:
      # - name: Free Disk Space (Ubuntu)
      #   uses: jlumbroso/free-disk-space@main
      #   with:
      #     # this might remove tools that are actually needed,
      #     # if set to "true" but frees about 6 GB
      #     tool-cache: false

      #     # all of these default to true, but feel free to set to
      #     # "false" if necessary for your workflow
      #     android: true
      #     dotnet: true
      #     haskell: true
      #     large-packages: false
      #     docker-images: true
      #     swap-storage: true

      - uses: actions/checkout@v4

      - name: Install 1Password CLI
        uses: 1Password/install-cli-action@v1.0.0

      - name: Generate dotenv
        env:
          DOTENV_FILE: .env.${{ env.ENV_TYPE }}
          DOTENV_YML: .env.${{ env.ENV_NAME }}.yml
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          OP_VAULT_NAME: ${{ secrets.OP_VAULT_NAME }}
          OVERWRITE: true
        run: |
          ACTIONS_STEP_DEBUG=false
          ./internal/scripts/get-op-ratelimit.sh

          # get env yml from 1password
          yarn --cwd internal op:get:$ENV_TYPE

          # mask sensitive values
          # internal/scripts/gha-mask.sh

          # generate dotenv
          yarn --cwd internal gen:env

          # Inject Logto Apps envs
          echo "LOGTO__ALP_APP__CLIENT_ID='GlEUkUOlpdpKgl01BrEVR'" >> $DOTENV_FILE
          echo "LOGTO__ALP_APP__CLIENT_SECRET='2X2hFU4BiW44odwB0OwjtJoQxtX7E5'" >> $DOTENV_FILE
          echo "LOGTO__ALP_SVC__CLIENT_ID='FcvGMfGsNm8QNdt9aCRuX'" >> $DOTENV_FILE
          echo "LOGTO__ALP_SVC__CLIENT_SECRET='IoJRGVHm05P8B0XRmqLozdK2U7TN1p'" >> $DOTENV_FILE
          echo "LOGTO__ALP_DATA__CLIENT_ID='zUkAG2MRaNmnMTWHBzlVb'" >> $DOTENV_FILE
          echo "LOGTO__ALP_DATA__CLIENT_SECRET='vgkToG2nuxzRDU7yMhAHiz5m1VZgLk'" >> $DOTENV_FILE

          echo DOCKER_TAG_NAME=$DOCKER_TAG_NAME | tee -a $DOTENV_FILE | tee -a $GITHUB_STEP_SUMMARY

      - name: Load dotenv from 1password
        uses: 1password/load-secrets-action@v2
        id: op-load-secret
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          REGISTRY_USERNAME: "op://${{ secrets.OP_VAULT_NAME }}/az-alpCR/username"
          REGISTRY_PASSWORD: "op://${{ secrets.OP_VAULT_NAME }}/az-alpCR/password"

      # - name: 1password ratelimit end
      #   env:
      #     OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      #   run: |
      #     ./internal/scripts/get-op-ratelimit.sh

      # - name: Upload stats.yml artifact
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: stats
      #     retention-days: 30
      #     path: |
      #       ${{ github.job }}*.yml

      #- name: Login to ACR
      #  uses: docker/login-action@v3.1.0
      #  with:
      #    registry: alpcr.azurecr.io
      #    username: ${{ env.REGISTRY_USERNAME }}
      #    password: ${{ env.REGISTRY_PASSWORD }}
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - uses: docker/setup-buildx-action@v3
        id: builder1
        with:
          config: .github/buildkitd.toml

      - name: Docker
        run: |
          docker system prune -af

      - name: Docker compose build
        run: |
          # Build DataNode services
          yarn build:minerva   --builder ${{ steps.builder1.outputs.name }}

      - name: Builder cache cleanup
        run: |
          docker buildx prune -af

      - name: Initalize Logto
        run: |
          yarn init:logto

      - name: Docker compose up Local Mode
        uses: nick-fields/retry@v3
        id: retry
        with:
          timeout_seconds: 1800
          retry_wait_seconds: 100
          max_attempts: 3
          retry_on: any
          command: |
            # Run DataNode services without sql-editor
            yarn start:minerva
            DC_EXIT_CODE=$?
            DOCKER_STATUS_FILE=../docker-status-${GITHUB_RUN_ID:-ghRunId}-$(date '+%Y%m%dT%H%M%S').txt | tee -a $GITHUB_ENV
            docker ps --format {{.Names}},{{.Status}} 2> /dev/null | sort | tee $DOCKER_STATUS_FILE | tee -a $GITHUB_STEP_SUMMARY
            [ $DC_EXIT_CODE = 0 ] || { echo EXIT DC_EXIT_CODE=$DC_EXIT_CODE && exit $DC_EXIT_CODE; }

      - name: Log status
        if: success() || failure()
        run: |
          echo DC_EXIT_CODE=$DC_EXIT_CODE | tee -a $GITHUB_STEP_SUMMARY
          echo RETRY_EXIT_CODE=${{ steps.retry.outputs.exit_code }} | tee -a $GITHUB_STEP_SUMMARY
          echo RETRY_OUTCOME=${{ steps.retry.outcome }} | tee -a $GITHUB_STEP_SUMMARY
          echo RETRY_TOTAL_ATTEMPTS=${{ steps.retry.outputs.total_attempts }} | tee -a $GITHUB_STEP_SUMMARY
          DC_FAIL_COUNT=$(grep -icE "starting|unhealthy" $DOCKER_STATUS_FILE|| true)
          echo DC_FAIL_COUNT=$DC_FAIL_COUNT | tee -a $GITHUB_STEP_SUMMARY

      - name: Logs minerva
        if: success() || failure()
        run: |
          yarn ci:logs:minerva

      - name: Clean Docker compose
        if: always()
        run: |
          # Clean DataNode services
          yarn clean:minerva
          docker system prune -af
