name: Docker Build Push Called

on:
  workflow_call:
    inputs:
      AZ_REG_REPOSITORY:
        required: true
        type: string
      DOCKER_BUILD_CONTEXT_PATH:
        default: "."
        required: false
        type: string
      DOCKER_BUILD_FILE_PATH:
        required: true
        type: string
      DOCKER_BUILD_PULL_BOOL_STR:
        default: "false"
        required: false
        type: string
      DOCKER_BUILD_PUSH_BOOL_STR:
        default: "false"
        required: false
        type: string
      DOCKER_IMG_TAG_NAME:
        required: true
        type: string
      GIT_BRANCH_NAME:
        required: true
        type: string
      GIT_COMMIT_ID__PLUGINS_REPO:
        default: main
        required: false
        type: string
      GIT_REPO_FULL_NAME:
        required: true
        type: string
      GIT_SSH_PRIVATE_KEYS:
        default: "null"
        required: false
        type: string

jobs:
  build-push-prune:
    name: ${{ inputs.AZ_REG_REPOSITORY }}
    runs-on: ubuntu-latest
    env:
      AZ_REG_FQDN: ${{ vars.AZ_REG_NAME }}.azurecr.io
      AZ_REG_NAME: ${{ vars.AZ_REG_NAME }}
      AZ_REG_PRUNE_DAYS: ${{ vars.AZ_REG_PRUNE_DAYS || '20' }}
      AZ_REG_PRUNE_ENABLE_DELETE: ${{ vars.AZ_REG_PRUNE_ENABLE_DELETE || 'false' }}
      AZ_REG_PRUNE_FORCE_ANALYZE: ${{ vars.AZ_REG_PRUNE_FORCE_ANALYZE || 'false' }}
      AZ_REG_PRUNE_KEEP_REGEX: ${{ vars.AZ_REG_PRUNE_KEEP_REGEX }}
      DOCKER_BUILD_DISABLE: ${{ vars.DOCKER_BUILD_DISABLE || 'false' }}
      DOCKER_BUILD_PUSH_BOOL_OVERRIDE: ${{ vars.DOCKER_BUILD_PUSH_BOOL_OVERRIDE || 'false' }}
      GIT_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: inputs
        shell: bash
        env:
          DOCKER_BUILD_CONTEXT_PATH: ${{ inputs.DOCKER_BUILD_CONTEXT_PATH }}
          DOCKER_BUILD_FILE_PATH: ${{ inputs.DOCKER_BUILD_FILE_PATH }}
          DOCKER_BUILD_PULL_BOOL_STR: ${{ inputs.DOCKER_BUILD_PULL_BOOL_STR }}
          DOCKER_BUILD_PUSH_BOOL_STR: ${{ inputs.DOCKER_BUILD_PUSH_BOOL_STR }}
          DOCKER_IMG_TAG_NAME: ${{ inputs.DOCKER_IMG_TAG_NAME }}
          GIT_BRANCH_NAME: ${{ inputs.GIT_BRANCH_NAME }}
          GIT_COMMIT_ID__PLUGINS_REPO: ${{ inputs.GIT_COMMIT_ID__PLUGINS_REPO }}
          GIT_REPO_FULL_NAME: ${{ inputs.GIT_REPO_FULL_NAME }}
        run: |
          echo AZ_REG_REPOSITORY=$AZ_REG_REPOSITORY | tee -a $GITHUB_STEP_SUMMARY

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.GIT_BRANCH_NAME }}
          repository: ${{ inputs.GIT_REPO_FULL_NAME }}
          token: ${{ secrets.CI_PAT }}

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZ_REG_FQDN }}
          username: ${{ env.AZ_REG_USERNAME }}
          password: ${{ env.AZ_REG_PASSWORD }}

      - name: SSH_AUTH_SOCK if GIT_SSH_PRIVATE_KEYS is null
        shell: bash
        if: ${{ inputs.GIT_SSH_PRIVATE_KEYS == 'null' }}
        run: |
          ssh-agent -s | sed -e 's/;.*//' -e '/^echo/d' | tee -a $GITHUB_ENV

      - name: SSH_AUTH_SOCK if GIT_SSH_PRIVATE_KEYS is not null
        uses: webfactory/ssh-agent@v0.9.0
        if: ${{ inputs.GIT_SSH_PRIVATE_KEYS != 'null' }}
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY_STARBOARD_WRAP }}
            ${{ secrets.SSH_PRIVATE_KEY_NOTEBOOK_BASE }}

      - name: Process Git & SSH config for Docker build context
        if: ${{ inputs.GIT_SSH_PRIVATE_KEYS != 'null' }}
        run: |
          cp -r ~/.gitconfig  ~/.ssh .github/
          cd .github/
          sed 's|/home/runner|/root|g' -i.bak .ssh/config

      - uses: docker/setup-buildx-action@v3
        id: builder

      - name: Purge docker images and cache
        if: ${{ vars.DOCKER_BUILD_DISABLE != 'true' }}
        run: |
          docker image prune -af
          docker buildx prune -af

      - name: Build and push
        uses: docker/build-push-action@v6
        if: ${{ vars.DOCKER_BUILD_DISABLE != 'true' }}
        with:
          builder: ${{ steps.builder.outputs.name }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          # ulimit: nofile=1048576:1048576
          platforms: "linux/amd64"
          context: ${{ inputs.DOCKER_BUILD_CONTEXT_PATH }}
          pull: ${{ inputs.DOCKER_BUILD_PULL_BOOL_STR == 'true' }}
          file: ${{ inputs.DOCKER_BUILD_FILE_PATH }}
          push: ${{ inputs.DOCKER_BUILD_PUSH_BOOL_STR == 'true' }}
          tags: ${{ vars.AZ_REG_NAME }}.azurecr.io/${{ inputs.AZ_REG_REPOSITORY }}:${{ inputs.DOCKER_IMG_TAG_NAME }}
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
          build-args: |
            docker_image_prefix=${{ vars.AZ_REG_NAME }}.azurecr.io
            GIT_COMMIT_ARG=${{ github.sha }}
            D2E_PLUGIN_REPO=${{ vars.D2E_PLUGIN_REPO }}
            GIT_COMMIT_ID__PLUGINS_REPO=${{ inputs.GIT_COMMIT_ID__PLUGINS_REPO }}
            GIT_TOKEN__PLUGINS_REPO_READ=${{ secrets.GIT_TOKEN__PLUGINS_REPO_READ }}

      - name: Post purge
        if: ${{ vars.DOCKER_BUILD_DISABLE != 'true' }}
        run: |
          docker system prune -af

          - name: Prune ACR Images created before vars.AZ_REG_PRUNE_DAYS_TAGGED
          if: env.AZ_REG_PRUNE_FORCE_ANALYZE == 'true' || env.GIT_BRANCH_NAME == 'develop'
          id: prune-images
          continue-on-error: true
          env:
            AZ_REG_PASSWORD: ${{ secrets.AZ_REGISTRY_PASSWORD }}
            AZ_REG_REPOSITORY: ${{ matrix.name }}
            AZ_REG_USERNAME: ${{ vars.AZ_REGISTRY_USERNAME }}
          run: |
            npx --suppess-warnings zx scripts/analyze-acr.mjs
            if [ $AZ_REG_PRUNE_ENABLE_DELETE = true ]; then
              echo "INFO . manifests delete ..."
              sh "private-manifests-delete.sh"
            else
              echo "INFO . manifests delete skipped"
            fi

      - name: Upload ACR manifests artifacts
        if: env.AZ_REG_PRUNE_FORCE_ANALYZE == 'true' || env.GIT_BRANCH_NAME == 'develop'
        uses: actions/upload-artifact@v4
        with:
          name: acr-manifests
          retention-days: 30
          path: |
            private-manifests*
