name: Azure Container Registry Prune

on:
  workflow_dispatch:
  push:
  workflow_call:
    inputs:
      AZ_REGISTRY_REPOSITORY:
        required: false
        default: "xxx"
        type: string
      DOCKER_BUILD_CONTEXT:
        required: false
        default: "xxx"
        type: string
      DOCKER_BUILD_FILE_PATH:
        required: false
        default: "xxx"
        type: string
      DOCKER_BUILD_PULL_BOOL:
        required: false
        default: "false"
        type: string
    secrets:
      AZ_REGISTRY_USERNAME:
        required: true
      AZ_REGISTRY_PASSWORD:
        required: true

jobs:
  az-reg-prune:
    name: azure registry prune
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          AZ_REGISTRY_REPOSITORY: ${{ inputs.AZ_REGISTRY_REPOSITORY || vars.AZ_REGISTRY_REPOSITORY }}
          DOCKER_BUILD_CONTEXT: ${{ inputs.DOCKER_BUILD_CONTEXT }}
          DOCKER_BUILD_FILE_PATH: ${{ inputs.DOCKER_BUILD_FILE_PATH }}
          DOCKER_BUILD_PULL_BOOL: ${{ inputs.DOCKER_BUILD_PULL_BOOL }}
        run: |
          echo AZ_REGISTRY_REPOSITORY=$AZ_REGISTRY_REPOSITORY | tee -a $GITHUB_STEP_SUMMARY
          echo DOCKER_BUILD_CONTEXT=$DOCKER_BUILD_CONTEXT | tee -a $GITHUB_STEP_SUMMARY
          echo DOCKER_BUILD_FILE_PATH=$DOCKER_BUILD_FILE_PATH | tee -a $GITHUB_STEP_SUMMARY
          echo DOCKER_BUILD_PULL_BOOL=$DOCKER_BUILD_PULL_BOOL | tee -a $GITHUB_STEP_SUMMARY
