name: Azure Container Registry Prune

on:
  workflow_dispatch:
  push:
  workflow_call:
    inputs:
      GIT_BRANCH_NAME:
        required: true
        type: string
      GIT_REPO_FULL_NAME:
        required: true
        type: string
      AZ_REGISTRY_REPOSITORY:
        required: true
        type: string
      DOCKER_BUILD_CONTEXT:
        required: true
        default: "xxx"
        type: string
      DOCKER_BUILD_FILE_PATH:
        required: true
        default: "xxx"
        type: string
      DOCKER_BUILD_PULL_BOOL:
        required: true
        type: string

jobs:
  build-push-prune:
    name: ${{ inputs.AZ_REGISTRY_REPOSITORY }}
    runs-on: ubuntu-latest
    steps:
      - name: echo
        shell: bash
        env:
          AZ_REGISTRY_REPOSITORY: ${{ inputs.AZ_REGISTRY_REPOSITORY || vars.AZ_REGISTRY_REPOSITORY }}
          DOCKER_BUILD_CONTEXT: ${{ inputs.DOCKER_BUILD_CONTEXT }}
          DOCKER_BUILD_FILE_PATH: ${{ inputs.DOCKER_BUILD_FILE_PATH }}
          DOCKER_BUILD_PULL_BOOL: ${{ inputs.DOCKER_BUILD_PULL_BOOL }}
          GIT_BRANCH_NAME: ${{ inputs.GIT_BRANCH_NAME }}
          GIT_REPO_FULL_NAME: ${{ inputs.GIT_REPO_FULL_NAME }}
        run: |
          echo AZ_REGISTRY_REPOSITORY=$AZ_REGISTRY_REPOSITORY | tee -a $GITHUB_STEP_SUMMARY
          echo DOCKER_BUILD_CONTEXT=$DOCKER_BUILD_CONTEXT | tee -a $GITHUB_STEP_SUMMARY
          echo DOCKER_BUILD_FILE_PATH=$DOCKER_BUILD_FILE_PATH | tee -a $GITHUB_STEP_SUMMARY
          echo DOCKER_BUILD_PULL_BOOL=$DOCKER_BUILD_PULL_BOOL | tee -a $GITHUB_STEP_SUMMARY
          echo GIT_BRANCH_NAME=$GIT_BRANCH_NAME | tee -a $GITHUB_STEP_SUMMARY
          echo GIT_REPO_FULL_NAME=$GIT_REPO_FULL_NAME | tee -a $GITHUB_STEP_SUMMARY

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.GIT_BRANCH_NAME }}
          repository: ${{ inputs.GIT_REPO_FULL_NAME }}
          token: ${{ secrets.CI_PAT }}

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: alpcr.azurecr.io
          username: ${{ secrets.AZ_REGISTRY_USERNAME }}
          password: ${{ secrets.AZ_REGISTRY_PASSWORD }}

      - name: Get docker tag name
        id: docker_tag
        shell: bash
        run: |
          if [ $GIT_BRANCH_NAME == "develop" ]; then
            echo "DOCKER_IMG_TAG_NAME=develop" | tee -a $GITHUB_OUTPUT
            echo "DOCKER_IMG_IS_PUSH=true" | tee -a $GITHUB_OUTPUT
          elif [ $GITHUB_EVENT_NAME = "workflow_dispatch" ]; then
              echo "DOCKER_IMG_TAG_NAME=$GIT_BRANCH_NAME" | tee -a $GITHUB_OUTPUT
              echo "DOCKER_IMG_IS_PUSH=true" | tee -a $GITHUB_OUTPUT
          else
              echo "DOCKER_IMG_IS_PUSH=false" | tee -a $GITHUB_OUTPUT
              echo "DOCKER_IMG_TAG_NAME=$(echo ${{ github.sha }} | cut -c1-8)" | tee -a $GITHUB_OUTPUT
          fi
