name: Azure Container Registry Prune

on:
  workflow_dispatch:
  push:
  workflow_call:
    inputs:
      AZ_REGISTRY_REPOSITORY:
        required: true
        type: string
      DOCKER_BUILD_CONTEXT:
        required: true
        type: string
      DOCKER_BUILD_FILE_PATH:
        required: true
        type: string
      DOCKER_BUILD_PULL_BOOL:
        required: true
        type: string
      DOCKER_IMG_IS_PUSH:
        required: true
        type: string
      DOCKER_IMG_TAG_NAME:
        required: true
        type: string
      GIT_BRANCH_NAME:
        required: true
        type: string
      GIT_REPO_FULL_NAME:
        required: true
        type: string

jobs:
  build-push-prune:
    name: ${{ inputs.AZ_REGISTRY_REPOSITORY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.GIT_BRANCH_NAME }}
          repository: ${{ inputs.GIT_REPO_FULL_NAME }}
          token: ${{ secrets.CI_PAT }}

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: alpcr.azurecr.io
          username: ${{ secrets.AZ_REGISTRY_USERNAME }}
          password: ${{ secrets.AZ_REGISTRY_PASSWORD }}

      - name: echo
        shell: bash
        env:
          AZ_REGISTRY_REPOSITORY: ${{ inputs.AZ_REGISTRY_REPOSITORY || vars.AZ_REGISTRY_REPOSITORY }}
          DOCKER_BUILD_CONTEXT: ${{ inputs.DOCKER_BUILD_CONTEXT }}
          DOCKER_BUILD_FILE_PATH: ${{ inputs.DOCKER_BUILD_FILE_PATH }}
          DOCKER_BUILD_PULL_BOOL: ${{ inputs.DOCKER_BUILD_PULL_BOOL }}
          GIT_BRANCH_NAME: ${{ inputs.GIT_BRANCH_NAME }}
          GIT_REPO_FULL_NAME: ${{ inputs.GIT_REPO_FULL_NAME }}
        run: |
          echo AZ_REGISTRY_REPOSITORY=$AZ_REGISTRY_REPOSITORY | tee -a $GITHUB_STEP_SUMMARY
          echo DOCKER_BUILD_CONTEXT=$DOCKER_BUILD_CONTEXT
          echo DOCKER_BUILD_FILE_PATH=$DOCKER_BUILD_FILE_PATH
          echo DOCKER_BUILD_PULL_BOOL=$DOCKER_BUILD_PULL_BOOL
          echo GIT_BRANCH_NAME=$GIT_BRANCH_NAME
          echo GIT_REPO_FULL_NAME=$GIT_REPO_FULL_NAME
          echo DOCKER_IMG_TAG_NAME=$DOCKER_IMG_TAG_NAME
          echo DOCKER_IMG_IS_PUSH=$DOCKER_IMG_IS_PUSH

      - uses: docker/setup-buildx-action@v3
        id: builder

      - name: Purge docker images and cache
        run: |
          docker image prune -af
          docker buildx prune -af

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.builder.outputs.name }}
          platforms: "linux/amd64"
          context: ${{ inputs.DOCKER_BUILD_CONTEXT }}
          pull: ${{ inputs.DOCKER_BUILD_PULL_BOOL }}
          file: ${{ inputs.DOCKER_BUILD_FILE_PATH }}
          push: ${{ inputs.DOCKER_IMG_IS_PUSH }}
          tags: alpcr.azurecr.io/${{ inputs.AZ_REGISTRY_REPOSITORY }}:${{ inputs.DOCKER_IMG_TAG_NAME }}
          build-args: |
            docker_image_prefix=alpcr.azurecr.io
            GIT_COMMIT_ARG=${{ github.sha }}
