name: build plugin

on:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches:
      - develop

env:
  GIT_CI_BRANCH_NAME: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./functions
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@alp-os"
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@data2evidence"
      - name: Update version
        run: jq --arg v "-$(date +%s)-$GITHUB_SHA" '.version+=$v' package.json > tmppkg; mv tmppkg package.json
      - name: cp pkg
        run: cp package.json package.org.json
      - name: mkdir
        run: sudo mkdir -p /usr/src/plugin/node_modules/@alp-os/d2e-functions
      - name: chown
        run: sudo chown runner:docker /usr/src/plugin/node_modules/@alp-os/d2e-functions
      - name: npminstall
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PH_TOKEN }}
      - name: cp src
        run: cp -a . /usr/src/plugin/node_modules/@alp-os/d2e-functions
      - name: npm build
        working-directory: /usr/src/plugin/node_modules/@alp-os/d2e-functions
        run: npm run build
      - name: Publish
        working-directory: /usr/src/plugin/node_modules/@alp-os/d2e-functions
        run: |
          if [[ $GIT_CI_BRANCH_NAME == 'develop' ]]; then 
            npm publish
          else 
            npm publish --dry-run
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v5
        if: github.ref_name == 'develop'
        with:
          package-name: "d2e-functions"
          package-type: "npm"
          min-versions-to-keep: 3
          delete-only-pre-release-versions: "true"
      - name: Pack
        working-directory: /usr/src/plugin/node_modules/@alp-os/d2e-functions
        run: |
          if [[ $GIT_CI_BRANCH_NAME == 'develop' ]]; then
            NPM_FILENAME=$(npm pack)
            echo "NPM_FILENAME=$NPM_FILENAME" >> $GITHUB_ENV
          fi
      - name: Push
        uses: svenstaro/upload-release-action@v2
        if: ${{ env.GIT_CI_BRANCH_NAME == 'develop' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /usr/src/plugin/node_modules/@alp-os/d2e-functions/${{ env.NPM_FILENAME }}
          tag: latest
          target_commit: develop
          prerelease: true
          overwrite: true
          asset_name: d2e-functions.tgz
